# A full list of config variables is available at:
# https://supabase.com/docs/guides/hosting/platform/self-hosting

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = ["https://localhost:8081"]
jwt_expiry = 3600
enable_refresh_token_rotation = false

[functions.automation-api]
verify_jwt = false

[functions.sync-telegram-chats]
verify_jwt = false

[functions.dump-stats]
enabled = true
verify_jwt = true
import_map = "./functions/dump-stats/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/dump-stats/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/dump-stats/*.html" ]

[functions.proxy-media]
enabled = true
verify_jwt = false

[functions.media-relay]
enabled = true
verify_jwt = false

[functions.whatsapp-media-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-media-proxy/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-media-proxy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-media-proxy/*.html" ]

[functions.whatsapp-tech-provider-auth]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-tech-provider-auth/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-tech-provider-auth/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-tech-provider-auth/*.html" ]

[functions.meta-webhook]
enabled = true
verify_jwt = false

[functions.telegram-webhook]
enabled = true
verify_jwt = false

[functions.whatsapp-webhook]
enabled = true
verify_jwt = false

[functions.social-oauth-callback]
enabled = true
verify_jwt = false

[functions.social-oauth-init]
enabled = true
verify_jwt = false

