export const ENV = {

SUPABASE_URL: Deno.env.get("SUPABASE_URL")!,
SUPABASE_SERVICE_ROLE_KEY: Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,

TELEGRAM_TOKEN: Deno.env.get("TELEGRAM_TOKEN")!,
WHATSAPP_TOKEN: Deno.env.get("WHATSAPP_TOKEN")!,
WHATSAPP_PHONE_ID: Deno.env.get("WHATSAPP_PHONE_ID")!,

X_API_KEY: Deno.env.get("X_API_KEY")!,
X_API_SECRET: Deno.env.get("X_API_SECRET")!,
X_ACCESS_TOKEN: Deno.env.get("X_ACCESS_TOKEN")!,
X_ACCESS_SECRET: Deno.env.get("X_ACCESS_SECRET")!,

META_ACCESS_TOKEN: Deno.env.get("META_ACCESS_TOKEN")!,
INSTAGRAM_USER_ID: Deno.env.get("INSTAGRAM_USER_ID")!,

YOUTUBE_TOKEN: Deno.env.get("YOUTUBE_TOKEN")!,

LINKEDIN_TOKEN: Deno.env.get("LINKEDIN_TOKEN")!,

PINTEREST_TOKEN: Deno.env.get("PINTEREST_TOKEN")!,

TIKTOK_TOKEN: Deno.env.get("TIKTOK_TOKEN")!,

SNAPCHAT_TOKEN: Deno.env.get("SNAPCHAT_TOKEN")!

}